### ISSUE TITLE
[Feature request] Resolution-aware image assets

### ISSUE THREAD

**Issue by JCKodel** [leancodepl/flutter_webp#10]
Flutter has different folders for different asset sizes:

```
.../my_icon.png       (mdpi baseline)
.../1.5x/my_icon.png  (hdpi)
.../2.0x/my_icon.png  (xhdpi)
.../3.0x/my_icon.png  (xxhdpi)
.../4.0x/my_icon.png  (xxxhdpi)
```
(source: https://docs.flutter.dev/ui/assets/assets-and-images#resolution-aware)

It would be nice to provide an original image that should always be 4.0x and then this package resolves all resolutions, for example: 

```
Source image: 256x256 pixels named "square.png".
```

This should create this folder structure:

```
square.png (64x64 pixels)
1.5x/square.png (96x96 pixels)
2.0x/square.png (128x128 pixels)
3.0x/square.png (192x192 pixels)
4.0x/square.png (256x256 pixels)
```

**Comment by Albert221** [comment]
Hello @JCKodel! Thanks for your interest in the `webp` package.

Your idea is a great example for an additional asset transformer that may be developed, but it is out of scope of the `webp` package. `webp` is solely for running the `cwebp` program on Flutter's assets.
